//! Generate `disk.img`, the sample image used by the other examples.
//!
//! Layout: a 16 MiB MBR-partitioned image with
//!
//! * partition 1 — 8 MiB, FAT16 LBA (`0x0E`), bootable, formatted with
//!   `embedded-fatfs` and pre-populated with a few sample files;
//! * partition 2 — 7 MiB, type `0x83` (Linux), containing a magic
//!   marker so the multi-partition example has something non-FAT to
//!   peek at.
//!
//! Usage:
//!
//! ```text
//! cargo run --example make_disk_image          # writes ./disk.img
//! cargo run --example make_disk_image -- foo.img
//! ```

use std::env;
use std::path::PathBuf;

use embedded_fatfs::{format_volume, FileSystem, FormatVolumeOptions, FsOptions};
use embedded_io_adapters::tokio_1::FromTokio;
use embedded_io_async::{Seek, SeekFrom, Write};
use embedded_partitions::mbr::{
    Chs, Mbr, PartitionEntry, PartitionType, MBR_SIZE, PARTITION_ENTRY_SIZE, SECTOR_SIZE,
};
use tokio::fs::OpenOptions;
use tokio::io::AsyncWriteExt;

const DISK_SECTORS: u32 = 32 * 1024; // 16 MiB
const PART1_LBA: u32 = 2048; // 1 MiB-aligned start
const PART1_SECTORS: u32 = 16 * 1024; // 8 MiB
const PART2_LBA: u32 = PART1_LBA + PART1_SECTORS;
const PART2_SECTORS: u32 = DISK_SECTORS - PART2_LBA;

const DISK_SIGNATURE: u32 = 0xCAFE_BABE;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let path: PathBuf = env::args()
        .nth(1)
        .unwrap_or_else(|| "disk.img".to_string())
        .into();

    let total_bytes = u64::from(DISK_SECTORS) * SECTOR_SIZE;
    println!(
        "Creating {} ({} MiB)",
        path.display(),
        total_bytes / (1024 * 1024)
    );

    // 1. Allocate the backing file at the right size.
    {
        let file = OpenOptions::new()
            .create(true)
            .read(true)
            .write(true)
            .truncate(true)
            .open(&path)
            .await?;
        file.set_len(total_bytes).await?;
    }

    // 2. Write the MBR sector (boot signature, disk signature, two
    //    primary partition entries).
    let part1 = PartitionEntry::new(
        true,
        Chs::LBA_SENTINEL,
        PartitionType::Fat16Lba,
        Chs::LBA_SENTINEL,
        PART1_LBA,
        PART1_SECTORS,
    );
    let part2 = PartitionEntry::new(
        false,
        Chs::LBA_SENTINEL,
        PartitionType::Linux,
        Chs::LBA_SENTINEL,
        PART2_LBA,
        PART2_SECTORS,
    );

    let mut mbr_sector = [0u8; MBR_SIZE];
    let p1_off = 446;
    let p2_off = p1_off + PARTITION_ENTRY_SIZE;
    mbr_sector[p1_off..p1_off + PARTITION_ENTRY_SIZE].copy_from_slice(&part1.to_bytes());
    mbr_sector[p2_off..p2_off + PARTITION_ENTRY_SIZE].copy_from_slice(&part2.to_bytes());
    mbr_sector[440..444].copy_from_slice(&DISK_SIGNATURE.to_le_bytes());
    mbr_sector[510] = 0x55;
    mbr_sector[511] = 0xAA;

    {
        let mut file = OpenOptions::new().write(true).open(&path).await?;
        file.write_all(&mbr_sector).await?;
        file.flush().await?;
    }

    // 3. Re-open through embedded-partitions, format partition 1 as FAT
    //    and drop sample files in. Then write a marker into partition 2.
    let file = OpenOptions::new()
        .read(true)
        .write(true)
        .open(&path)
        .await?;
    let io = FromTokio::new(file);
    let mut mbr = Mbr::new(io).await?;

    {
        let mut slice = mbr.open_partition(0).await?;
        format_volume(&mut slice, FormatVolumeOptions::new()).await?;
    }

    {
        let mut slice = mbr.open_partition(0).await?;
        let fs = FileSystem::new(&mut slice, FsOptions::new()).await?;
        {
            let root = fs.root_dir();

            let mut readme = root.create_file("README.TXT").await?;
            readme
                .write_all(
                    b"Sample disk image generated by\r\n\
                      `cargo run --example make_disk_image`.\r\n",
                )
                .await?;
            readme.flush().await?;

            let logs = root.create_dir("LOGS").await?;
            let mut hello = logs.create_file("HELLO.LOG").await?;
            hello
                .write_all(b"Hello from the embedded-partitions sample image.\r\n")
                .await?;
            hello.flush().await?;

            let mut big = root.create_file("BIG.BIN").await?;
            let chunk = [0xA5_u8; 512];
            for _ in 0..16 {
                big.write_all(&chunk).await?;
            }
            big.flush().await?;
        }
        fs.unmount().await?;
    }

    {
        let mut slice = mbr.open_partition(1).await?;
        slice.seek(SeekFrom::Start(0)).await?;
        slice.write_all(b"NOT-FAT-PARTITION\n").await?;
        slice.flush().await?;
    }

    println!("done.");
    Ok(())
}
