on: [push, pull_request]

name: CI

jobs:
  check:
    name: Build
    strategy:
      matrix:
        include:
          - rust_version: nightly
            run_tests: true
          - rust_version: 1.85
            run_tests: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rust_version == 'nightly' }}
    env:
      RUST_LOG: warn
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}

      - name: Print Rust compiler version
        run: rustc --version

      - name: Build embedded-fatfs (all feature combinations)
        run: |
          cargo build -p embedded-fatfs
          cargo build -p embedded-fatfs --examples
          cargo build -p embedded-fatfs --no-default-features
          cargo build -p embedded-fatfs --no-default-features --features lfn
          cargo build -p embedded-fatfs --no-default-features --features alloc,lfn,unicode
          cargo build -p embedded-fatfs --no-default-features --features alloc,lfn,unicode,defmt
          cargo build -p embedded-fatfs --no-default-features --features alloc,lfn,unicode,log

      - name: Test embedded-fatfs
        # always supply dirty-file-panic to find internal flushing issues
        run: cargo test -p embedded-fatfs --verbose --features dirty-file-panic
        if: ${{ matrix.run_tests }}

      - name: Build embedded-partitions (all feature combinations)
        run: |
          cargo build -p embedded-partitions
          cargo build -p embedded-partitions --examples
          cargo build -p embedded-partitions --no-default-features --features defmt
          cargo build -p embedded-partitions --no-default-features --features log

      - name: Test embedded-partitions
        run: cargo test -p embedded-partitions --verbose
        if: ${{ matrix.run_tests }}
