on: [push, pull_request]

name: CI

jobs:
  check:
    name: Build
    strategy:
      matrix:
        include:
          - rust_version: nightly
            run_tests: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rust_version == 'nightly' }}
    env:
      RUST_LOG: warn
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust_version }}
          override: true

      - name: Print Rust compiler version
        run: rustc --version

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p embedded-fatfs

      - name: Run cargo build --examples
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p embedded-fatfs --examples

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features dirty-file-panic # always supply dirty-file-panic to find internal flushing issues
        if: ${{ matrix.run_tests }}

      - name: Run cargo build - no_std
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p embedded-fatfs --no-default-features

      - name: Run cargo build - no_std, lfn
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p embedded-fatfs --no-default-features --features lfn

      - name: Run cargo build - no_std, alloc, lfn, unicode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p embedded-fatfs --no-default-features --features alloc,lfn,unicode
      - name: Run cargo build - no_std, alloc, lfn, unicode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p embedded-fatfs --no-default-features --features alloc,lfn,unicode
      - name: Run cargo build - Check defmt
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p embedded-fatfs --no-default-features --features alloc,lfn,unicode,defmt
      - name: Run cargo build - Check log
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p embedded-fatfs --no-default-features --features alloc,lfn,unicode,log
